imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1
        assets_version_format: %%2$s/%%1$s

    default_locale:  %locale%
    trust_proxy_headers: false
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        [ DiscussioneMainBundle, DiscussioneDiscussionBundle ]
    filters:
        cssrewrite: ~
        less:
            node_paths: ["%kernel.root_dir%/../node_modules"]
            node: %node_bin%
        coffee:
            bin: "%kernel.root_dir%/../node_modules/coffee-script/bin/coffee"
            node: %node_bin%
            apply_to: "\.coffee$"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Mongo Configuration
doctrine_mongodb:
    connections:
        default:
            server: %database_host%
            options: {}

    default_database: %database_name%

    document_managers:
        default:

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# RabbitMQ Configuration
old_sound_rabbit_mq:
    connections:
        default:
            host:     %rabbit_host%
            port:     %rabbit_port%
            user:     %rabbit_user%
            password: %rabbit_password%
            vhost:    %rabbit_vhost%

    producers:
        unprocessed:
            connection: default
            exchange_options: { name: 'unprocessed', type: direct }
            queue_options: {name: 'unprocessed'}

    consumers:
        processed:
            connection: default
            exchange_options: { name: 'processed', type: direct }
            queue_options: { name: 'processed' }
            callback: discussione.consumer.processed

