services:
    discussione_message.service.message:
        class: Discussione\MessageBundle\Service\MessageService
        arguments: ["@old_sound_rabbit_mq.unprocessed_producer"]

    discussione_message.consumer.processed:
        class: Discussione\MessageBundle\Consumer\ProcessedConsumer